//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookSerVice
    {
        public int BookSerViceID { get; set; }
        public Nullable<System.DateTime> SerViceDateOrder { get; set; }
        public Nullable<int> IDSerVice { get; set; }
        public string NameCus { get; set; }
        public string PhoneCus { get; set; }
        public string DressCus { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> DateBookSerVice { get; set; }
        public string NameSerVice { get; set; }
        public Nullable<System.DateTime> CheckIntDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
    
        public virtual SerVice SerVice { get; set; }
    }
}
