//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderRoom()
        {
            this.Quanlies = new HashSet<Quanly>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string NameCus { get; set; }
        public string PhoneCus { get; set; }
        public string DressCus { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string StatusOrder { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CusID { get; set; }
        public string RoomName { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string DiscountCode { get; set; }
        public int? ThueID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quanly> Quanlies { get; set; }
    }
}
