//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhuThu
    {
        public int PhuThuID { get; set; }
        public string TenPhuThu { get; set; }
        public Nullable<decimal> TangTienPhuThu { get; set; }
    }
}
