//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerVice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SerVice()
        {
            this.BookSerVices = new HashSet<BookSerVice>();
        }
    
        public int SerViceID { get; set; }
        public string ServiceDescription { get; set; }
        public Nullable<decimal> PriceSerVice { get; set; }
        public string ImageSerVice { get; set; }
        public string NameSerVice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookSerVice> BookSerVices { get; set; }
    }
}
